[package]
org = "dilanperera"
name = "twillio_test"
version = "0.1.0"
distribution = "2201.8.0"

[[dependency]]
org="ballerinax"
name = "twilioresource"
version = "2.0.0"
repository = "local"

[[dependency]]
org="ballerinax"
name = "twilioremote"
version = "2.0.0"
repository = "local"

[build-options]
observabilityIncluded = true
